### ISSUE TITLE
The link of the pretrained models can't be reached

### ISSUE THREAD

**Issue by Anonymous-so** [lizuoyue/sate_to_ground#4]
Hi, thanks for the inspiring work.
The link of pretrained models [https://drive.google.com/file/d/15RKzyrMn-h7ZcfGt92n5r6Vd1HIbnMj1/view?usp=sharing] can't be reached. Is the download link updated? If it is, will the new download link be shared?

**Comment by lizuoyue** [comment]
Hello, you can find everything here:

https://drive.google.com/file/d/1dVmR3rb96SSEyKXzY5hqx3a80Ud_NSXK
https://drive.google.com/file/d/1F-pjOC4xJDEsg4inPNvgO3NOY9PQ6OMq
https://drive.google.com/file/d/1OA3So5yt-jXbkav85IQ574OGCu670dpj
